import os
from datetime import date
from pathlib import Path
import markdown as md

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Digest — {date}</title>
<style>
body {{ font-family: -apple-system, "Segoe UI", sans-serif; max-width: 740px; margin: 2em auto; padding: 0 1em; color: #1a1a1a; line-height: 1.55; }}
header {{ border-bottom: 2px solid #eee; padding-bottom: .5em; margin-bottom: 1.5em; }}
header h1 {{ margin: 0; font-size: 1.6em; }}
header time {{ color: #888; font-size: .9em; }}
h2 {{ margin-top: 1.75em; font-size: 1.15em; border-bottom: 1px solid #eee; padding-bottom: .25em; }}
a {{ color: #1a5fb4; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
li {{ margin-bottom: .6em; }}
footer {{ margin-top: 3em; padding-top: 1em; border-top: 1px solid #eee; color: #888; font-size: .85em; }}
</style>
</head>
<body>
<header>
<h1>AI Digest</h1>
<time datetime="{date}">{date}</time>
</header>
<article>
{body}
</article>
<footer>Generated by NewsAgent</footer>
</body>
</html>
"""


def archive(markdown_text: str) -> tuple[Path, str | None]:
    today = date.today().isoformat()
    digests_dir = Path(__file__).parent / "digests"
    digests_dir.mkdir(exist_ok=True)
    path = digests_dir / f"{today}.html"
    body = md.markdown(markdown_text, extensions=["extra", "sane_lists"])
    path.write_text(TEMPLATE.format(date=today, body=body))

    url = None
    repo = os.environ.get("GITHUB_REPOSITORY")
    if repo and "/" in repo:
        owner, name = repo.split("/", 1)
        url = f"https://{owner}.github.io/{name}/digests/{today}.html"
    return path, url
